# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa4996aeff617b070eb6a081c96bf316e84ce9ffcea924a3356363295234357ef4973f6ce60b068db5b974b7f1f62d572d61f1673e2be1c00b12f1a5a5a0791

test:
  secret_key_base: ea07405a8fc00e4c90d347c75b8e4816663dc5869d8ba28ecdf12dd6e3e15a2b708414d3c43b6f2490bcbe843f8b3c5f3ef19e19ae9b94cc0db7cdd6bae73050

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
